### ISSUE TITLE
You can have your github or frontendmentor profile link in "href"

### ISSUE THREAD

**Issue by aman-atg** [jaseveen/Frontendmentor1#1]
Instead of this 
~` <a  href="#">Jaseveen</a> `~
You can have : 
`<a href="https://github.com/jaseveen"> Jaseveen </a>`
OR
`<a href= "https://frontendmentor.io/profile/jaseveen"> Jaseveen </a>`

**Comment by jaseveen** [comment]
thanks! chnged :)

pt., 3 kwi 2020 o 13:27 Aman Ansari <notifications@github.com> napisał(a):
